/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wc;

import java.sql.Connection;
import java.sql.*;
import javax.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import jdbc.core.*;

/**
 *
 * @author Pushkar
 */
public class Simulate extends javax.swing.JFrame {

    /**
     * Creates new form Simulate
     */
    static String user="raj";
    static int cid=2;
    static int cido=3;
    String url = "jdbc:oracle:thin:@workstation:1521:XE";
    String username = "raj";
    String password = "raj123";
    public Simulate(String abc,int clb) {
        user=abc;
        cid=clb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 350, 130, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter Opponent Team");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 350, 200, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BATTLE!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 400, 180, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CLUB ID", "Club", "played", "win", "draw", "lose", "points"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 20, 530, 240);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 470, 180, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 470, 140, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bg2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 620, 350);

        setBounds(0, 0, 637, 595);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String st=jTextField1.getText();
        int opp=Integer.parseInt(st);
        System.out.println(opp);
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt=conn.createStatement();
            Statement stmt1=conn.createStatement();
            Statement stmt2=conn.createStatement();
            Statement stmt3=conn.createStatement();
            Statement stmt4=conn.createStatement();
            Statement stmt5=conn.createStatement();
            Statement stmt6=conn.createStatement();
            Statement stmt7=conn.createStatement();
            int a,b;
            /*ResultSet rs2=stmt.executeQuery("select club_id from clubs where club_name='"+jTextField1.getText()+"'");
            rs2.next();
            cido=rs2.getInt(1);*/
    /*        ResultSet rs=stmt.executeQuery("select rating from  players,Club_Player where players.player_id=Club_Player.player_id and cid="+opp);
            int a=0;
            while(rs.next()){
                a=a+rs.getInt(1);
                                
                
            }
            System.out.println(a);
            //rs.close();
          /*  ResultSet rs3=stmt.executeQuery("select club_id from clubs,User_Club where usid='"+user+"'");
            rs3.next();
            cido=rs3.getInt(1);
            ResultSet rs1=stmt1.executeQuery("select rating from  players,Club_Player where players.player_id=Club_Player.player_id and cid="+cid);
            int b=0;
            while(rs1.next()){
                b=b+rs1.getInt(1);
                //System.out.println("hello");
                                
                
            }
            System.out.println(b);
            rs.close(); 
            ResultSet rs3=stmt.executeQuery("select get_total("+cid+") from dual");
            rs3.next();
            a=rs3.getInt(1);
            ResultSet rss3=stmt.executeQuery("select get_total("+opp+") from dual");
            rss3.next();
            b=rss3.getInt(1);*/
      CallableStatement callableStatement =conn.prepareCall("{?=call get_total(?)}");
           callableStatement.registerOutParameter(1, java.sql.Types.INTEGER);
            callableStatement.setInt(2,opp);
             callableStatement.executeQuery();
             a=callableStatement.getInt(1);
    //System.out.println(a);
    CallableStatement callableStatement2 =conn.prepareCall("{?=call get_total(?)}");
           callableStatement2.registerOutParameter(1, java.sql.Types.INTEGER);
            callableStatement2.setInt(2,cid);
             callableStatement2.executeQuery();
             b=callableStatement2.getInt(1);
    //System.out.println(b);
    
    
            if(a>b)
            {
                JOptionPane.showMessageDialog(this,"You Lose");
                stmt2.executeQuery("update League set p=p+1,w=w+1,points=points+3 where club_id="+opp);
                stmt3.executeQuery("update League set p=p+1,l=l+1 where club_id="+cid);
            }
            else if(b>a)
            {
                JOptionPane.showMessageDialog(this,"You Win");
                stmt4.executeQuery("update League set p=p+1,w=w+1,points=points+3 where club_id="+cid);
                stmt5.executeQuery("update League set p=p+1,l=l+1  where club_id="+opp);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Draw");
                stmt6.executeQuery("update League set p=p+1,d=d+1,points=points+1 where where club_id="+cid);
                stmt7.executeQuery("update League set p=p+1,d=d+1,points=points+1 where club_id="+opp);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        DefaultTableModel tb1=(DefaultTableModel)jTable1.getModel();
        String sql="select club_id,club_name,p,w,l,d,points from League";
        
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(sql);
            tb1.setRowCount(0);
            while(rs.next()){
                Object row[]=new Object[7];
                row[0]=rs.getObject(1).toString();
                row[1]=rs.getObject(2).toString();
                row[2]=rs.getObject(3).toString();
                row[3]=rs.getObject(4).toString();
                row[4]=rs.getObject(5).toString();
                row[5]=rs.getObject(6).toString();
               row[6]=rs.getObject(7).toString();
                
                                
                tb1.addRow(row);
            }
            rs.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }        // TODO add your hand
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
DefaultTableModel tb1=(DefaultTableModel)jTable1.getModel();
        String sql="select club_id,club_name,p,w,d,l,points from League natural join clubs";
        
        try{
            Connection conn=DriverManager.getConnection(url,username,password);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(sql);
            tb1.setRowCount(0);
            while(rs.next()){
                Object row[]=new Object[7];
               row[0]=rs.getObject(1).toString();
                row[1]=rs.getObject(2).toString();
                row[2]=rs.getObject(3).toString();
                row[3]=rs.getObject(4).toString();
                row[4]=rs.getObject(5).toString();
                row[5]=rs.getObject(6).toString();
               row[6]=rs.getObject(7).toString();
                
                                
                tb1.addRow(row);
            }
            rs.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Login l=new Login();
            this.setVisible(false);
            l.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulate(user,cid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
